"use client";

import Link from "next/link";
import { BrainCircuit, ArrowUpRight } from "lucide-react";
import type { NewsArticle, User, UserPreferences } from "@/types";
import { cn, getCategoryColor, timeAgo } from "@/lib/utils";
import { useReader } from "@/lib/reader-context";
import { avatarFor } from "@/lib/placeholder";
import ArticleImage from "@/components/ui/ArticleImage";

export function ProfileCard({ user }: { user: User }) {
  return (
    <div className="card p-5 text-center">
      <img
        src={avatarFor(user)}
        alt={user.name}
        className="w-16 h-16 rounded-full object-cover mx-auto ring-4 ring-brand-50"
      />
      <p className="mt-3 font-semibold text-ink-900">{user.name}</p>
      <p className="text-xs text-ink-400">{user.persona}</p>
      <Link href="/profile" className="btn-secondary w-full mt-4 text-sm py-2">
        Manage Preferences
      </Link>
    </div>
  );
}

export function FavoriteCategories({ preferences }: { preferences: UserPreferences }) {
  return (
    <div className="card p-5">
      <p className="text-sm font-semibold text-ink-900 mb-3">Favorite Categories</p>
      <div className="flex flex-wrap gap-2">
        {preferences.preferred_categories.map((cat) => {
          const c = getCategoryColor(cat);
          return (
            <Link
              key={cat}
              href={`/discover?category=${encodeURIComponent(cat)}`}
              title={`Browse ${cat}`}
              className={cn(
                "badge hover:ring-2 hover:ring-offset-1 hover:ring-brand-300 transition-all",
                c.bg,
                c.text
              )}
            >
              <span className={cn("w-1.5 h-1.5 rounded-full", c.dot)} />
              {cat}
            </Link>
          );
        })}
      </div>
    </div>
  );
}

export function RecentlyRead({ articles }: { articles: NewsArticle[] }) {
  const { openArticle } = useReader();

  return (
    <div className="card p-5">
      <div className="flex items-center justify-between mb-3">
        <p className="text-sm font-semibold text-ink-900">Recently Read</p>
        {articles.length > 0 && (
          <Link
            href="/history"
            className="text-xs font-medium text-brand-600 hover:text-brand-700"
          >
            View all
          </Link>
        )}
      </div>
      <div className="space-y-3">
        {articles.slice(0, 4).map((a) => (
          <button
            key={a.news_id}
            onClick={() => openArticle(a)}
            className="w-full flex items-center gap-3 group text-left"
          >
            <ArticleImage
              article={a}
              width={120}
              height={120}
              className="w-11 h-11 rounded-lg object-cover shrink-0"
            />
            <span className="min-w-0 flex-1">
              <span className="block text-xs font-medium text-ink-900 line-clamp-2 leading-snug group-hover:text-brand-600 transition-colors">
                {a.title}
              </span>
              <span className="block text-[11px] text-ink-400 mt-0.5">
                {timeAgo(a.published_at)}
              </span>
            </span>
          </button>
        ))}
        {articles.length === 0 && (
          <p className="text-xs text-ink-400">No reading history yet.</p>
        )}
      </div>
    </div>
  );
}

export function GruModelCard() {
  return (
    <div className="card p-5 bg-navy-gradient text-white border-0">
      <div className="flex items-center gap-2">
        <div className="w-9 h-9 rounded-lg bg-white/10 flex items-center justify-center">
          <BrainCircuit size={18} className="text-violet-400" />
        </div>
        <div>
          <p className="text-sm font-semibold">Powered by GRU Model</p>
          <p className="text-[11px] text-white/60">Sequential Recommendation Network</p>
        </div>
      </div>
      <p className="text-xs text-white/55 mt-3 leading-relaxed">
        Your recommendations are generated by a GRU neural network trained on
        sequential reading behavior across all users.
      </p>
      <Link
        href="/model-insights"
        className="mt-4 inline-flex items-center gap-1 text-xs font-semibold text-brand-400 hover:text-brand-300"
      >
        View Model Insights
        <ArrowUpRight size={13} />
      </Link>
    </div>
  );
}
